import { Region } from "./interface";

export const rdcslData: Array<Region> = [
  {
    name: "Eastern",
    districts: [
      {
        name: "Kailahu",
        chiefdoms: [
          "Dea",
          "Jahn",
          "Jawie",
          "Kissi Kama",
          "Kissi Teng",
          "Kissi Tongi",
          "Kpeje Bongre",
          "Kpeje West",
          "Luawa",
          "Malema",
          "Mandu",
          "Njaluahun",
          "Penguia",
          "Upper Bambara",
          "Yawei",
        ],
      },
      {
        name: "Kenema",
        chiefdoms: [
          "Dama",
          "Dodo",
          "Gaura",
          "Gorama Mende",
          "Kandu Leppiama",
          "Koya",
          "Langrama",
          "Lower Bambara",
          "Malegohun",
          "Niawa",
          "Nomo",
          "Nongowa",
          "Simbaru",
          "Small Bo",
          "Tunkia",
          "Wandor",
          "Kenema City",
        ],
      },
      {
        name: "Kono",
        chiefdoms: [
          "Faima",
          "Gbane",
          "Gbane Kandor",
          "Gbense",
          "Goroma Kono",
          "Kamara",
          "Lei",
          "Mafindor",
          "Nimikoro",
          "Nimiyama",
          "Sandor",
          "Soa",
          "Tankora",
          "Toli",
          "Koidu City",
        ],
      },
    ],
  },
  {
    name: "Northern",
    districts: [
      {
        name: "Bombali",
        chiefdoms: [
          "Biriwa",
          "Bombali Shebora",
          "Bombali Siari",
          "Gbanti",
          "Gbendembu",
          "Kamaranka",
          "Magbaimba Ndorwahun",
          "Makari",
          "Mara",
          "gowahun",
          "Paki Masabong",
          "Safroko Limba",
          "Makani City",
        ],
      },
      {
        name: "Falaba",
        chiefdoms: [
          "Delemandugu",
          "Dembelia",
          "Dembelia-Sinkunia",
          "Folosaba",
          "Kamadu Yiraia",
          "Kebelia",
          "Kulor Saradu",
          "Mongo",
          "Morifindugu",
          "Neya",
          "Nyedu",
          "Sulima",
          "Wollay Barawa",
        ],
      },
      {
        name: "Koinadugu",
        chiefdoms: [
          "Diang",
          "Gbonkobon Kayaka",
          "Kalian",
          "Kamukeh",
          "Kasunko KaKellian",
          "Nieni",
          "Sengbe",
          "Tamiso",
          "Wara Wara Bafodia",
          "Wara Wara Yagala",
        ],
      },
      {
        name: "Tonkolili",
        chiefdoms: [
          "Dansogoia",
          "Gbonkolenkeni/Masankong",
          "Kafe",
          "Kalanthuba",
          "Kholifa Mabang",
          "Kholifa Mamuntha/ Mayosso",
          "Kholifa Rowala",
          "Kunike Barina",
          "Kunike Folawusu",
          "Kunike Sanda",
          "Malal",
          "Mayeppoh",
          "Poli",
          "Sambaya",
          "Simiria",
          "Tane",
          "Yele",
          "Yoni Mabanta",
          "Yoni Mamaila",
        ],
      },
    ],
  },
  {
    name: "North Western",
    districts: [
      {
        name: "Kambia",
        chiefdoms: [
          "Bramaia",
          "Dixon",
          "Gbinle",
          "Khonimaka",
          "Magbema",
          "Mambolo",
          "Masungbala",
          "Munu Thalla",
          "Samu",
          "Tonko Limba",
        ],
      },
      {
        name: "Karena",
        chiefdoms: [
          "Buya",
          "Dibia",
          "Gbanti",
          "Libeisaygahun/Gbombahun",
          "Mafonda Makerembay",
          "Romende",
          "Safroko",
          "Sanda Loko",
          "Sanda Magbolontor",
          "Sanda Tendaran",
          "Sella Limba",
          "Tambakha Simibungie",
          "Tambakha Yobangie",
        ],
      },
      {
        name: "Port Loko",
        chiefdoms: [
          "Bakeh Loko",
          "Bureh",
          "Kaffu Bullom",
          "Kamasondo",
          "Kasseh",
          "Koya",
          "Loko Masama",
          "Maconteh",
          "Maforki",
          "Makama",
          "Marampa",
          "Masimera",
          "Thainkatopa",
          "Port Loko City",
        ],
      },
    ],
  },
  {
    name: "Southern",
    districts: [
      {
        name: "Bo",
        chiefdoms: [
          "Badjia",
          "Bagbo",
          "Bagbwe(Bagbe)",
          "Boama",
          "Bongor",
          "Bumpe Ngao",
          "Gbo",
          "Jaiama",
          "Kakua",
          "Komboya",
          "Lugbu",
          "Niawa Lenga",
          "Selenga",
          "Tikonko",
          "Valunia",
          "Wonde",
          "Bo City",
        ],
      },
      {
        name: "Bonthe",
        chiefdoms: [
          "Bendu-Cha",
          "Bum",
          "Dema",
          "Imperri",
          "Jong",
          "Kpanda Kemo",
          "Kwamebai Krim",
          "Nongoba",
          "Sittia",
          "Sogbeni",
          "Yawbeko",
          "Bonthe Urban",
        ],
      },
      {
        name: "Moyamba",
        chiefdoms: [
          "Bagruwa",
          "Bumpeh",
          "Dasse",
          "Fakunya",
          "Kagboro",
          "Kaiyamba",
          "Kamajei",
          "Kongbora",
          "Kori",
          "Kowa",
          "Banta",
          "Ribbi",
          "Timdale",
          "Upper Banta",
        ],
      },
      {
        name: "Pujehun",
        chiefdoms: [
          "Barri",
          "Galliness",
          "Kabonde",
          "Kpaka",
          "Makpele",
          "Malen",
          "Mano Sakrim",
          "Panga",
          "Panga krim",
          "Pejeh (Futa peje)",
          "Perri",
          "Soro Gbema",
          "Sowa",
          "Yakemu Kpukumu",
        ],
      },
    ],
  },
  {
    name: "Western",
    districts: [
      {
        name: "Rural",
        chiefdoms: ["Koya", "Mountain Rural", "Waterloo Rural", "York Rural"],
      },
      {
        name: "Urban",
        chiefdoms: [
          "Central 1",
          "Central 2",
          "East 1",
          "East 2",
          "East 3",
          "West 1",
          "West 2",
          "West 3",
        ],
      },
    ],
  },
];